t1 = Teacher.create(name:"Filius Flitwick")
t2 = Teacher.create(name:"Pomona Sprout")
t3 = Teacher.create(name:"Sybill Trelawney")
t4 = Teacher.create(name:"Remus Lupin")
t5 = Teacher.create(name:"Rubeus Hagrid")
t6 = Teacher.create(name:"Severus Snape")
t7 = Teacher.create(name:"Rolanda Hooch")
t8 = Teacher.create(name:"Minerva McGonagall")


ClassPeriod.create(subject:"Charms", teacher_id:t1.id, period:1, level:5)
ClassPeriod.create(subject:"Charms", teacher_id:t1.id, period:2, level:4)
ClassPeriod.create(subject:"Charms", teacher_id:t1.id, period:3, level:3)
ClassPeriod.create(subject:"Charms", teacher_id:t1.id, period:4, level:2)
ClassPeriod.create(subject:"Charms", teacher_id:t1.id, period:5, level:1)

ClassPeriod.create(subject:"Herbology", teacher_id:t2.id, period:1, level:5)
ClassPeriod.create(subject:"Herbology", teacher_id:t2.id, period:2, level:4)
ClassPeriod.create(subject:"Herbology", teacher_id:t2.id, period:3, level:3)
ClassPeriod.create(subject:"Herbology", teacher_id:t2.id, period:4, level:2)
ClassPeriod.create(subject:"Herbology", teacher_id:t2.id, period:5, level:1)

ClassPeriod.create(subject:"Divination", teacher_id:t3.id, period:1, level:5)
ClassPeriod.create(subject:"Divination", teacher_id:t3.id, period:2, level:4)
ClassPeriod.create(subject:"Divination", teacher_id:t3.id, period:3, level:3)
ClassPeriod.create(subject:"Divination", teacher_id:t3.id, period:4, level:2)
ClassPeriod.create(subject:"Divination", teacher_id:t3.id, period:5, level:1)

ClassPeriod.create(subject:"Defene Against The Dark Arts", teacher_id:t4.id, period:1, level:5)
ClassPeriod.create(subject:"Defene Against The Dark Arts", teacher_id:t4.id, period:2, level:4)
ClassPeriod.create(subject:"Defene Against The Dark Arts", teacher_id:t4.id, period:3, level:3)
ClassPeriod.create(subject:"Defene Against The Dark Arts", teacher_id:t4.id, period:4, level:2)
ClassPeriod.create(subject:"Defene Against The Dark Arts", teacher_id:t4.id, period:5, level:1)

ClassPeriod.create(subject:"Care of Magical Creaturea", teacher_id:t5.id, period:1, level:5)
ClassPeriod.create(subject:"Care of Magical Creaturea", teacher_id:t5.id, period:2, level:4)
ClassPeriod.create(subject:"Care of Magical Creaturea", teacher_id:t5.id, period:3, level:3)
ClassPeriod.create(subject:"Care of Magical Creaturea", teacher_id:t5.id, period:4, level:2)
ClassPeriod.create(subject:"Care of Magical Creaturea", teacher_id:t5.id, period:5, level:1)

ClassPeriod.create(subject:"Potions", teacher_id:t6.id, period:1, level:5)
ClassPeriod.create(subject:"Potions", teacher_id:t6.id, period:2, level:4)
ClassPeriod.create(subject:"Potions", teacher_id:t6.id, period:3, level:3)
ClassPeriod.create(subject:"Potions", teacher_id:t6.id, period:4, level:2)
ClassPeriod.create(subject:"Potions", teacher_id:t6.id, period:5, level:1)

ClassPeriod.create(subject:"Flying", teacher_id:t7.id, period:1, level:5)
ClassPeriod.create(subject:"Flying", teacher_id:t7.id, period:2, level:4)
ClassPeriod.create(subject:"Flying", teacher_id:t7.id, period:3, level:3)
ClassPeriod.create(subject:"Flying", teacher_id:t7.id, period:4, level:2)
ClassPeriod.create(subject:"Flying", teacher_id:t7.id, period:5, level:1)

ClassPeriod.create(subject:"Transfiguration", teacher_id:t8.id, period:1, level:5)
ClassPeriod.create(subject:"Transfiguration", teacher_id:t8.id, period:2, level:4)
ClassPeriod.create(subject:"Transfiguration", teacher_id:t8.id, period:3, level:3)
ClassPeriod.create(subject:"Transfiguration", teacher_id:t8.id, period:4, level:2)
ClassPeriod.create(subject:"Transfiguration", teacher_id:t8.id, period:5, level:1)

Student.create(name:'Ron Weasley',)
Student.create(name:'Hermione Granger',)
Student.create(name:'Colin Creevey',)
Student.create(name:'Seamus Finnigan',)
Student.create(name:'Hannah Abbott',)
Student.create(name:'Pansy Parkinson',)
Student.create(name:'Zacharias Smith',)
Student.create(name:'Blaise Zabini',)
Student.create(name:'Draco Malfoy',)
Student.create(name:'Dean Thomas',)
Student.create(name:'Millicent Bulstrode',)
Student.create(name:'Ernie Macmillan',)
Student.create(name:'Vincent Crabbe',)
Student.create(name:'Gregory Goyle',)
Student.create(name:'Lavender Brown',)
Student.create(name:'Katie Bell',)
Student.create(name:'Parvati Patil',)
Student.create(name:'Dennis Creevey',)
Student.create(name:'Neville Longbottom',)
Student.create(name:'Ginny Weasley',)
Student.create(name:'Romilda Vane',)
Student.create(name:'Natalie McDonald',)
Student.create(name:'Euan Abercrombie',)
Student.create(name:'Penelope Clearwater',)
Student.create(name:'Roger Davies',)
Student.create(name:'Cho Chang',)
Student.create(name:'Michael Corner',)
Student.create(name:'Padma Patil',)
Student.create(name:'Luna Lovegood',)
Student.create(name:'Susan Bones',)
Student.create(name:'Justin Finch-Fletchley',)
Student.create(name:'Tracey Davis',)
Student.create(name:'Lilian Moon',)


# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)
# Student.create(name:'',)






# c1 = ClassPeriod.create(subject:"Transfiguration", teacher_id:t1.id)
# c2 = ClassPeriod.create(subject:"Biology", teacher_id:t1.id)
# c3 = ClassPeriod.create(subject:"Biology", teacher_id:t1.id)
# c4 = ClassPeriod.create(subject:"Robotics Engineering", teacher_id:t1.id)
# c5 = ClassPeriod.create(subject:"Robotics Engineering", teacher_id:t1.id)
# c6 = ClassPeriod.create(subject:"Freshmen Science 2", teacher_id:t1.id)